### ISSUE TITLE
Refresh closes application after a few seconds

### ISSUE THREAD

**Issue by Yoshi-RBLX** [xZeko-SRC/DevGoose#1]
So when I click refresh to get the process (as done in the tutorial video) it just goes for a few seconds and then just closes the app. I've tried it without goose game running, on the title screen, and in-game. It's still not working. I don't know if the download I got was broken or if it's the app itself that's just broken, but I can't seem to find a way to fix this. I know it worked for other people (ex: WDN2010, VHSquid) so I might have a bad download or PC, even. But I'm just not sure what the problem is. I haven't uninstalled and reinstalled the mod at the time of writing this so I'll reply to this on whether or not it works after that.

**Comment by Yoshi-RBLX** [comment]
Alright I've uninstalled and reinstalled the mod and it's still closing out.

**Comment by Yoshi-RBLX** [comment]
oh crap im blind ok i didnt honk so sorry

**Comment by Yoshi-RBLX** [comment]
uhh nevermind its STILL closing even tho i honk why

**Comment by xZeko-SRC** [comment]
It's not to do with devgoose, it's a smi_gui problem. A couple of things you can try is make sure there are no other programs apart from smi_gui and goose game open. There are some programs that don't like it and close. Dnspy will close it on refresh. Another one is check your antivirus. I heard kasperspy does not like smi_gui.

**Comment by Yoshi-RBLX** [comment]
i have dnspy, do i need to delete it or does it just not need to be opened bc it wasnt opened

**Comment by Yoshi-RBLX** [comment]
also my antivirus is disabled just in case

**Comment by xZeko-SRC** [comment]
Just don't have it opened with smi_gui. I'll try look into this further

**Comment by Yoshi-RBLX** [comment]
ill try uninstalling it too and ill see what that does since it wasnt opened. ill see if itll work

**Comment by xZeko-SRC** [comment]
You could try running it from administrator or there is an unofficial smi_gui update somewhere. This is an older version of it as it worked for me at the time.

**Comment by Yoshi-RBLX** [comment]
where would i be able to find the unofficial smi_gui version, also uninstalling dnspy not work

**Comment by xZeko-SRC** [comment]
You should be able to get it from unknowncheats. If it works I'll add it to the next update

**Comment by Yoshi-RBLX** [comment]
sorry to keep bothering you but i cant seem to find it, all i found was something for bloons

**Comment by xZeko-SRC** [comment]
No worries I am on mobile atm so it's harder then usual lol. You may need to sign up to download iirc. https://www.unknowncheats.me/forum/downloads.php?do=file&id=34970

**Comment by Yoshi-RBLX** [comment]
alright i registered an account and i downloaded the rar file from the site, ill tell you if it works. it might not bc of my pc but idk honestly ill still update you

**Comment by Yoshi-RBLX** [comment]
alright it worked, just replace the smi_gui application, include the smi exe just in case too and run it bc i did that, and replace the sharpmonoinjector and itll work, i got "untitled" to show up! :D tysm bro

**Comment by xZeko-SRC** [comment]
No worries enjoy! I'll update the exe for the new one soon.
