### ISSUE TITLE
How can i use this on Linux?

### ISSUE THREAD

**Issue by ghost** [xZeko-SRC/DevGoose#2]

**Comment by xZeko-SRC** [comment]
You will need a Sharp Mono Injector for the mod to run in Linux.
I don't have any specific Linux based software to recommend unfortunately.

**Comment by ghost** [comment]
> You will need a Sharp Mono Injector for the mod to run in Linux. I don't have any specific Linux based software to recommend unfortunately.

I cant really find a easy to use Injector that works.

**Comment by MonkeyInPrivate** [comment]
> > You will need a Sharp Mono Injector for the mod to run in Linux. I don't have any specific Linux based software to recommend unfortunately.
> 
> I cant really find a easy to use Injector that works.

Install the SteamTinkerLaunch program, click on game menu, scroll down and check "Use ICSInjector" then set ICSInjector wait to 30 seconds to give you time to honk. Currently I believe this mod is out of date so just wait for it to be updated.

**Comment by xZeko-SRC** [comment]
Please download https://github.com/xZeko-SRC/Honk-Menu

This should work with the linux version of Melonloader!
