### ISSUE TITLE
Trojan Virus Detected while downloading the DevGoose Menu

### ISSUE THREAD

**Issue by dubseth25** [xZeko-SRC/DevGoose#3]
can anyone verify if download this mod menu for goose game is actually a virus or is Microsoft defender just being paranoid? I literally cannot allow the download.

Trojan: Script / Wacatac . H!ml

**Comment by xZeko-SRC** [comment]
Join the goose speedrun discord they will verify it.. Or download the smi_gui from an external source.

**Comment by dubseth25** [comment]
dont exactly know what you mean so i probably wont do anything about it and just forget about it, sounded fun to be able to mod the game though, thats dissapointing

**Comment by xZeko-SRC** [comment]
Join and ask. https://discord.com/invite/MWDXaMXE

**Comment by xZeko-SRC** [comment]
As per the other issue. Removed smi_gui injector from the zip. Google and download the latest version of the injector, run the injector and select DevGoose Mod dll.
